### ISSUE TITLE
Import warning

### ISSUE THREAD

**Issue by GrunyD** [Skielex/slgbuilder#6]
Hello there, working on DTU QUAITOM project, would you look at something for us?

I don't think it causes problem with computation, but it is annoying. Every time I import this module I get the following:

`<frozen importlib._bootstrap>:241: UserWarning: enum class termtype not importable from thinmaxflow.src._maxflow. You are probably using a cpdef enum declared in a .pxd file that does not have a .py  or .pyx file.`

I am working with python 3.11.2 on Linux machine.

**Comment by Skielex** [comment]
~~Could you provide some more context? For instance, the code that triggers the warning.~~

Ok, I see the issue. The warning is actually in the `thinkmaxflow` package. I'll see if I can fix it quickly. If not, since it's not causing any real problems, I won't spend time on it now. You are of course welcome to make a PR in the [`thinmaxflow` repo](https://github.com/Skielex/thinmaxflow). There are also ways to suppress unwanted warnings in Python.

**Comment by Skielex** [comment]
I'm publishing a fix for `thinkmaxflow`.
